sudo: false
language: java
jdk: oraclejdk8
cache: apt
script: mvn install
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_success:
  - mvn clean install jacoco:report coveralls:report
